  version: '3.8'

  services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    backend-app:
      build: 
        context: .
        dockerfile: Dockerfile
        args:
          APPS_COUNT: ${APPS_COUNT:-1}  # Use 1 as default if APPS_COUNT is not set
      ports:
        - "8000:8000"
      depends_on: 
        - postgres
      environment:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}

    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle'


  volumes:
    postgres_data:
