  version: "3.9"

  services:
    postgres:
      extends:
        file: docker-compose.base.yml
        service: database
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"

    postgres-test:
      extends:
        file: docker-compose.base.yml
        service: database
      environment:
        POSTGRES_DB: ${POSTGRES_DB}_test
      ports:
        - "5433:5433"

    redis:
      image: redis:6.2-alpine
      ports:
        - "6379:6379"
      restart: always
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data
      
    app:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      env_file: "./.env"
      ports:
          - "8000:8000"
      expose:
        - 8000
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - ./src:/src
        - app-logs:/var/log/app
      
      networks:
        - backend

    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus
      ports:
        - "9090:9090"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle'

  volumes:
    pgdata:
      driver: local
    app-logs:
      driver: local
    prometheus-data:
      driver: local
    redis-data:
      driver: local

  networks:
    backend: