[tool.poetry]
name = "fastapi-API"
version = "0.0.1"
description = "A minimal repository for a FastAPI app instance"
authors = ["Bruno Peixoto <brunolnetto@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
a2wsgi = "==1.10.4"
aiohttp = "==3.9.3"
aiosignal = "==1.3.1"
altair = "==4.2.2"
matplotlib = "==3.7.5"
numpy = "==1.26.4"
pandas = "==2.2.1"
python-decouple = "==3.8"
scikit-learn = "==1.4.1.post1"
scipy = "==1.12.0"
seaborn = "==0.13.2"
streamlit = "==1.32.2"
streamlit-aggrid = "==0.3.5"
threadpoolctl = "==3.4.0"
toml = "==0.10.2"
alembic = "==1.13.1"
apache-airflow = "==2.6.0"
apache-airflow-providers-common-sql = "==1.11.1"
apache-airflow-providers-ftp = "==3.7.0"
apache-airflow-providers-http = "==4.10.0"
apache-airflow-providers-imap = "==3.5.0"
apache-airflow-providers-sqlite = "==3.7.1"
databases = "==0.6.0"
fastapi = "==0.68.0"
Flask = "==2.2.5"
Flask-AppBuilder = "==4.3.0"
Flask-Babel = "==2.0.0"
Flask-Caching = "==2.1.0"
Flask-JWT-Extended = "==4.6.0"
Flask-Limiter = "==3.5.1"
Flask-Login = "==0.6.3"
Flask-Session = "==0.7.0"
Flask-SQLAlchemy = "==2.5.1"
Flask-WTF = "==1.2.1"
gunicorn = "==21.2.0"
psycopg2-binary = "==2.9.9"
pendulum = "==3.0.0"
pytest = "==8.1.1"
SQLAlchemy = "==1.4.52"
SQLAlchemy-JSONField = "==1.0.2"
SQLAlchemy-Utils = "==0.41.2"
starlette = "==0.14.2"
uvicorn = "==0.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
