[tool.poetry]
name = "fastapi-airflow-use-case"
version = "0.0.1"
description = "A minimal repository for a FastAPI app and Airflow instance"
authors = ["Bruno Peixoto <brunolnetto@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
fastapi = "^0.110.0"
sqlalchemy = "^2.0.29"
pytest = "^8.1.1"
alembic = "^1.13.1"
databases = "^0.9.0"
flask = "^3.0.2"
gunicorn = "^21.2.0"
jinja2 = "^3.1.3"
psycopg2-binary = "^2.9.9"
pydantic = "^2.6.4"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
